AmirMizrahi/ChargeIT

- server/src/main/java/com/server/chargingStations/ChargingStation.java
- server/src/main/java/com/server/chargingStations/ChargingStationController.java
- server/src/main/java/com/server/chargingStations/ChargingStationRepository.java
- server/src/main/java/com/server/users/UserController.java
1. Added:
ChargingStationRepository interface.
ChargingStationController class.
2. Added TODO comments.
> Some ChargingStation work.

- server/src/main/java/com/server/chargingStations/ChargingStation.java
- server/src/main/java/com/server/users/User.java
- server/src/main/java/com/server/users/UserController.java
- server/src/main/java/com/server/users/UserNameAndPassword.java
- server/src/main/java/com/server/users/UserRepository.java
- server/src/main/resources/postMan/ChargeIT.postman_collection.json
1. Added: 
UserNameAndPassword class.
2. Added:
updateUserEmail
updateUserPhoneNumber
3. Added:
postMan collection.
> User&charging station

- server/src/main/java/com/server/GeoLocation.java
- server/src/main/java/com/server/chargingStations/ChargingStation.java
- server/src/main/java/com/server/chargingStations/ChargingStationController.java
- server/src/main/resources/postMan/ChargeIT.postman_collection.json
1. Added: 
/getAllChargingStationsLocations endpoint.
2. Added:
postMan /getAllChargingStationsLocations.
> 1. Added: /getAllChargingStationsLocations endpoint.

- server/pom.xml
- server/src/main/java/com/server/chargingStations/ChargingStationController.java
- server/src/main/java/com/server/users/UserController.java
- server/src/main/resources/application.properties
- server/src/main/resources/postMan/ChargeIT.postman_collection.json
Added: Sessions, authentications and restrictions.
> Sessions, authentications and restrictions.

- server/pom.xml
- server/src/main/java/com/server/chargingStations/ChargingStationController.java
- server/src/main/resources/templates/map.html
Added map.html file that show map (by using Google Maps API) and all the charging stations from the DB.
> Google Maps

- server/src/main/java/com/server/GeoLocation.java
- server/src/main/java/com/server/chargingStations/ChargingStation.java
- server/src/main/java/com/server/chargingStations/ChargingStationController.java
- server/src/main/java/com/server/chargingStations/ChargingStationJson.java
- server/src/main/java/com/server/chargingStations/ChargingStationRepository.java
- server/src/main/java/com/server/users/User.java
- server/src/main/java/com/server/users/UserController.java
- server/src/main/java/com/server/users/UserRepository.java
- server/src/main/resources/postMan/ChargeIT.postman_collection.json
Add: Input tests.
Add: ChargingStationJson class.
> Add: Input tests.

- server/src/main/java/com/server/chargingStations/ChargingStationController.java
- server/src/main/java/com/server/users/User.java
- server/src/main/java/com/server/users/UserController.java
- server/src/main/resources/postMan/ChargeIT.postman_collection.json
Added: 4 capabilities.
Added: 
- updatePricePerVolt.
- updateUserPassword.
- updateUserFirstName.
- updateUserLastName.
Updated: PostMan.
> Added: 4 capabilities.

- server/src/main/java/com/server/users/UserController.java
- server/src/main/resources/postMan/ChargeIT.postman_collection.json
Added: deleteUser.
Updated: PostMan.
> Added: deleteUser.

- server/src/main/java/com/server/chargingStations/ChargingStation.java
- server/src/main/java/com/server/chargingStations/ChargingStationController.java
- server/src/main/java/com/server/users/UserController.java
- server/src/main/resources/postMan/ChargeIT.postman_collection.json
Updated: PostMan.
Added: logout.
Fix: User cant create new chargingStation with existing location in DB.
> Added: logout.

- package.json
- server/src/main/java/com/server/test/EndpointTest.java
- server/src/main/java/com/server/users/UserController.java
- ui-rn6/chargeIT/App.js
- ui-rn6/chargeIT/package-lock.json
- ui-rn6/chargeIT/package.json
- ui-rn6/chargeIT/src/api/basicApi.js
- ui-rn6/chargeIT/src/context/AuthContext.js
- ui-rn6/chargeIT/src/screens/authentication/AuthForm.js
- ui-rn6/chargeIT/src/screens/authentication/Login.js
- ui-rn6/chargeIT/src/screens/authentication/Registration.js
continued authentication logic.
> UI basic screens

- ui-rn6/chargeIT/App.js
- ui-rn6/chargeIT/src/components/StationDetails.js
- ui-rn6/chargeIT/src/screens/authentication/Splash.js
- ui-rn6/chargeIT/src/screens/mainFlow/StationSelectScreen.js
- ui-rn6/chargeIT/src/screens/mainFlow/StationWatchScreen.js
- added station list watch page
- sdded  station details component
> - added station watch page

- server/src/main/java/com/server/chargingStations/ChargingStation.java
- server/src/main/java/com/server/chargingStations/ChargingStationController.java
- server/src/main/java/com/server/chargingStations/ChargingStationDTO.java
- server/src/main/java/com/server/chargingStations/ChargingStationRepository.java
- server/src/main/resources/postMan/ChargeIT.postman_collection.json
Add: Added ID for ChargingStation.
Update: All relevant endpoint that got GeoLocation now get ChargingStationId.
> Add: Added ID for ChargingStation.

- server/src/main/java/com/server/chargingStations/ChargingStationDTO.java
- server/src/main/java/com/server/users/UserController.java
- server/src/main/java/com/server/users/UserDTO.java
- server/src/main/resources/postMan/ChargeIT.postman_collection.json
Add: Added UserDTO and getUser().
> Add: Added UserDTO and getUser().

- server/src/main/java/com/server/chargingStations/ChargingStationController.java
- server/src/main/java/com/server/users/UserController.java
- server/src/main/java/com/server/users/UserDTO.java
- server/src/main/resources/postMan/ChargeIT.postman_collection.json
Add: Added chargingStationDTOS to UserDTO.
> Add: Added chargingStationDTOS to UserDTO.

- server/src/main/java/com/server/chargingStations/ChargingStationController.java
- server/src/main/java/com/server/users/UserController.java
Update: Removed session exception & replace with error code & message.
> Update: Removed session exception & replace with error code & message.

- server/src/main/java/com/server/chargingStations/ChargingStation.java
- server/src/main/java/com/server/chargingStations/ChargingStationController.java
- server/src/main/java/com/server/chargingStations/ChargingStationDTO.java
- server/src/main/java/com/server/chargingStations/ChargingStationJson.java
- server/src/main/java/com/server/users/UserController.java
- server/src/main/resources/postMan/ChargeIT.postman_collection.json
Added name to chargingStation & updateUser endpoint.
Add: Added station name to chargingStation.
Add: Added updateUser endpoint.
> Added name to chargingStation & updateUser endpoint.

- server/src/main/java/com/server/chargingStations/ChargingStationController.java
- server/src/main/resources/postMan/ChargeIT.postman_collection.json
Add: Added test to check communication with Simulator.
> Add: Added test to check communication with Simulator.

- ui-rn6/chargeIT/src/components/StationDetails.js
- ui-rn6/chargeIT/src/context/StationsContext.js
- ui-rn6/chargeIT/src/screens/mainFlow/StationSelectScreen.js
- ui-rn6/chargeIT/src/screens/mainFlow/StationWatchScreen.js
added distance to station
added charging request
> changed design

- ui-rn6/chargeIT/App.js
- ui-rn6/chargeIT/src/components/StationDetails.js
- ui-rn6/chargeIT/src/screens/authentication/EditProfile.js
- ui-rn6/chargeIT/src/screens/mainFlow/MyStations.js
- ui-rn6/chargeIT/src/screens/mainFlow/StationSelectScreen.js
- ui-rn6/chargeIT/src/screens/mainFlow/StationWatchScreen.js
- ui-rn6/chargeIT/src/screens/mainFlow/UserProfile.js
> update user works but without error handling

- server/src/main/resources/application.properties
> Update: Extra session time.

- server/src/main/java/com/server/chargingStations/ChargingStationController.java
> Core: Simulator integration.

- ui-rn6/chargeIT/src/screens/mainFlow/SelectChargingStation.js
> Merge screens

- server/src/main/java/com/server/ServerConfig.java
- server/src/main/java/com/server/chargingStations/ChargingStationController.java
- server/src/main/java/com/server/users/IsraeliCreditCard.java
- server/src/main/java/com/server/users/User.java
- server/src/main/java/com/server/users/UserController.java
- server/src/main/java/com/server/users/UserDTO.java
- server/src/main/resources/postMan/ChargeIT.postman_collection.json
Update: Makes sure that the user's current location does not exceed 50            meters from the station location.
Update: Update PostMan.
Update: You need a valid creditCard in order to charge.
Add:    Added ServerConfig class.
Add:    Added IsraeliCreditCard class.
Add:    Added IsraeliCreditCard to User class and isValidIsraeliCreditCard        to UserDTO.
Add:    Added updateUserCreditCard endpoint.
>  After Beta work

- server/src/main/java/com/server/chargingStations/ChargingStationController.java
- server/src/main/java/com/server/users/User.java
- server/src/main/java/com/server/users/UserController.java
- server/src/main/java/com/server/users/UserDTO.java
- server/src/main/java/com/server/users/money/IsraeliCreditCard.java
- server/src/main/java/com/server/users/money/MoneyTransaction.java
Add: Added MoneyTransaction Class.
Add: Added profit and payment history.
> Add: Added profit and payment history.

- server/src/main/java/com/server/chargingStations/ChargingStation.java
- server/src/main/java/com/server/chargingStations/ChargingStationController.java
- server/src/main/java/com/server/chargingStations/ChargingStationDTO.java
- server/src/main/java/com/server/chargingStations/Review.java
- server/src/main/resources/postMan/ChargeIT.postman_collection.json
Add: Added Review Class.
Add: Added addReview Endpoint.
> Add: Added addReview Endpoint.

- server/src/main/java/com/server/users/UserController.java
- server/src/main/resources/postMan/ChargeIT.postman_collection.json
Add: Added updateCreditCard option to "updateUser".
> Add: Added updateCreditCard option to "updateUser".

- server/src/main/java/com/server/chargingStations/ChargingStationController.java
- server/src/main/resources/postMan/ChargeIT.postman_collection.json
Add: Added "updateChargingStation" endpoint.
Add: Added "updateStationName" endpoint.
Add: Added "updateChargingStation" endpoint.
Update: "updatePricePerVolt" now check given charging station id to the request sender.
> Add: Added "updateChargingStation" endpoint.

- server/src/main/java/com/server/chargingStations/ChargingStation.java
- server/src/main/java/com/server/chargingStations/ChargingStationController.java
- server/src/main/java/com/server/users/User.java
- server/src/main/java/com/server/users/UserController.java
- server/src/main/resources/postMan/ChargeIT.postman_collection.json
ADD: Added getChargingStationIDuserCurrentlyUse ENDPOINT.
{
Add: Added the capability to get the Charging Station ID the user Currently Use.
Add: Added getChargingStationIDuserCurrentlyUse endpoint.
Update: User can now charge only from one charging station at a time.
}
> ADD: Added getChargingStationIDuserCurrentlyUse ENDPOINT.

- server/src/main/java/com/server/chargingStations/ChargingStationController.java
- server/src/main/java/com/server/users/UserController.java
- server/src/main/java/com/server/users/UserDTO.java
- server/src/main/resources/postMan/ChargeIT.postman_collection.json
Reviews, owner bug fix, money history.
Reviews moved to body.
Owner get paid and needs to pay when charging in its own charging station.
MoneyTransaction history removed from getUser endpoint and now on his own endpoint (getUserMoneyTransactions).
> Reviews, owner bug fix, money history.

- ui-rn6/chargeIT/src/api/basicApi.js
- ui-rn6/chargeIT/src/screens/mainFlow/CreateStation.js
- ui-rn6/chargeIT/src/screens/station/EditStation.js
- ui-rn6/chargeIT/src/screens/statistics/Bill.js
- ui-rn6/chargeIT/src/screens/statistics/Revenue.js
my payments
my profits
station edit page
> added design to
